### ISSUE TITLE
Test: 'Copy licence' option on Licence details page should be available to INST_ADM

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#1008]
Newly added functionality for v5.0 - a 'Copy this licence' option on the licence details page (e.g. https://www.kbplus.ac.uk/test/licenseDetails/index/3). Currently Copy option only displayed for users who can edit the licence being viewed. Since users will often want to copy template licences (which they can't edit) the Copy option needs to be available to any user with INST_ADM role

<img width="1145" alt="screen shot 2015-08-16 at 21 03 46" src="https://cloud.githubusercontent.com/assets/576174/9295116/b8e79dd2-445a-11e5-932f-d21eb01e6953.png">

**Comment by iyawnis** [comment]
Does this rule need to be focused on that specific action? Or is it ok to say that the licence will be editable if user is INST_ADM?

**Comment by iyawnis** [comment]
Ah I guess since its a template we dont want to let users edit it.

**Comment by ostephens** [comment]
Still an issue. Screenshot below of https://www.kbplus.ac.uk/test/licenseDetails/index/6 (which is a Template licence), using login kb+test2 which has INST_ADM role in relation to two Orgs - but don't get the 'Copy' option - get the message about "Actions available to editors only" instead:

<img width="1227" alt="screen shot 2015-08-18 at 21 26 01" src="https://cloud.githubusercontent.com/assets/576174/9341768/c1292182-45ef-11e5-89a0-4f9d4dd812d5.png">

**Comment by ianibo** [comment]
This is actually confusion caused by the issue not really clearly spelling out on what objects the role should be applied. @latusaki seems to have implemented a cancopy flag which is set if you have the INST_ADM role for any institution which the license is currently linked to as a Licensor. This materially the same as the check already on the page - you can copy the license if you already license it and you're an admin of the inst that licensed the work.

What I _think_ the issue should have asked for is the copy dropdown to be populated with a list of all orgs where the user has ROLE_ADM rights. If there are additional criteria to do with consortial membership then they should be set out clearly here so we can implement them as needed. Ioannis - can you revisit once @ostephens has refined / approved what I've suggested here.

**Comment by ostephens** [comment]
Agreed that the copy dropdown should be populated with a list of all the orgs where the user has INST_ADM role (and this is what happens when the copy menu appears). No additional rules in relation to consortia

As long as you have INST_ADM role in relation to at least one org, you can copy any licences you can view.

Hope this is clear now

**Comment by iyawnis** [comment]
I have used the following now:

``` groovy
    def admin_role = Role.findAllByAuthority("INST_ADM")
    result.canCopyOrgs = UserOrg.executeQuery("select uo.org from UserOrg uo where uo.user=(:user) and uo.formalRole=(:role) and uo.status in (:status)",[user:result.user,role:admin_role,status:[1,3]])
```

So, users will be able to copy a licence from licenceDetails/index if: 
- they have access to that licence already
- and there is an org where they have the role INST_ADM

Should the system admin be able to copy everywhere or that is not important/ should not happen?

**Comment by ostephens** [comment]
Thanks

System Admin - not important - they have to have an INST_ADM with the relevant Org to be able to do the copy
