### ISSUE TITLE
Compare Licences (KB+ Licence Properties) export

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#1034]
Which is the target release for this feature ? Also, the format will be the same as the custom property format in current licences exports?

**Comment by iyawnis** [comment]
I have reused the CSV export from currentLicences for this, added to 5.0.1

**Comment by iyawnis** [comment]
@ostephens I sent you an export from this screen, just double check that it doesn't need any more info, as it is going to test on next push.

**Comment by ostephens** [comment]
Hi Ioannis,

Think the format is generally OK but just to check:
- Assume that the export includes all the licences in the Comparison on the screen?
- Don't think the SEARCH TERMS header is needed here because it isn't based on a search/filtered set of licences, but of a list of licences chosen by the user

If removing the SEARCH TERMS header is problematic I don't think there is much harm including it, just that it is redundant in this case

**Comment by iyawnis** [comment]
- Yes all licences will be listed, on the example I sent you I compared two licences.
- Ok ill see if I can do something sensible for the header.
