### ISSUE TITLE
Time out of log-in

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#135]
After several minutes of inactivity (not sure exactly how long) the system seems to be automatically logging me out. Is this intentional? If the user is intentionally automatically logged out after x minutes of inactivity then there needs to be a clear warning/explanation about that somewhere, and a clear message on screen explaning what has happened, with a link to log back in again.

[cross ref: issue 1.4 in \KB+\Spec - Forms\KB+ initial usability review - HH - 06082012 - v2]

**Comment by ianibo** [comment]
Default session timeout is 30 mins.. _however_ that is somewhat dependent upon your clock and the server clock being in sync. Very hard to detect a timeout rather than a new user session to display a message explaining what has happened, and all tied up with distributed auth / shib issues. 

This is pretty standard behaviour for functional apps, only thing we can really do is to extend the timeout, but then you run into security considerations, particularly on shared machines.

Can add text saying "your session will be expired after 30 mins".. but need a steer on where that message should go so that it's not too obtrusive. How long should session timeout be extended?

**Comment by ostephens** [comment]
If still an issue should be picked up in UI review. No further action needed against this issue
