### ISSUE TITLE
Original note not displayed in note comment lightbox

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#232]
When viewing/making comments on a note a lightbox is used. The original note is not displayed in the lightbox, and the lightbox obscures the original note in the main screen.

**Comment by ianibo** [comment]
This can't be done at the moment because the comments are actually attached to alerts, not to notes, and alerts can be attached to lots of different contexts, not just notes. There's currently no easy way to get back from a comment to the alert and from the alert to the note. Suggest we put this into next phase and roll up with "Sorting out alerts"

**Comment by ostephens** [comment]
No longer required following change to notes functionality in 3.3
