### ISSUE TITLE
You can delete a subscription that is attached to a licence

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#243]
Which leaves the subscription accessible from the linked licence - and once you are looking at the detail of the subscription it isn't at all clear it is deleted

**Comment by ianibbo** [comment]
Heya..

I thought about this one when implementing... but then couldn't really see
a downside.. It's important we don't delete a license if there are
subscriptions attached as a sub can have many licenses, but the reverse is
not true.. There are no referential integrity downsides to "deleting" a
subscription with a license attached.

If this is an actual business requirement, can implement without hassles,
but couldn't work out the logic of it otherwise?

**Comment by ostephens** [comment]
I suspect the issue is really one of warning and display rather than wanting to prevent it completely.

At the moment there is no signal that a subscription is deleted, either on the link from the licence or when viewing the subscription details. We haven't really worked out what happens to the different categories of stuff that isn't 'current' (either by status or by date).

My view is we leave it as it is at the moment and document the behaviour, then work out how we want to handle it later

**Comment by ostephens** [comment]
Prompt for UI review in phase 2. No action necessary on this issue
