### ISSUE TITLE
Licensing Consortium role does not confer 'View' permissions?

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#292]
User that has an Editor role in JISC Collections (TestUserF: JC Admin [HH] / Xf8bVt77cA+Xr7ZXSNxoZbFuiOQ=@edina.ac.uk) cannot not edit a license that is linked to JISC Collections by the "Licensing Consortium" role.

Looking at http://test.kbplus.ac.uk/kbplus/licenseDetails/additionalInfo/1 as the user I see:

```
  <h2>The following organisations are granted the listed permissions from this licence</h2>
```

<table>
        <tr>
          <th>Organisation</th><th>Roles and Permissions</th>
        </tr>
        
          <tr>
            <td>IoP Publishing Limited</td>
            <td>
              Connected to this license through role Licensor.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
              </ul>
            </td>
          </tr>
        
          <tr>
            <td>JISC Collections</td>
            <td>
              Connected to this license through role Licensing Consortium.<br/>
              This role grants the following permissions to members of that org whose membership role also includes the permission<br/>
              <ul>
                
                  <li>edit 
                      
                        [Granted]
                      
 
                  </li>
                
              </ul>
            </td>
          </tr>
        
      </table>

```
  <h2>Logged in user permissions</h2>
```

<table>
        <tr>
          <th>Affiliated via Role</th><th>Permissions</th>
        </tr>
        
          <tr>
            <td>Affiliated to JISC Collections with role Editor</td>
            <td>
              <ul>
                
                  <li>view</li>
                
                  <li>edit</li>
                
              </ul>
            </td>
          </tr>
          
        
      </table>

**Comment by ianibo** [comment]
Yep, missing ref data.. Modified upgrade script to do the following:

insert into org_perm_share(perm_id,rdv_id) values ( @edit_perm, @licencee_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @view_perm, @licencee_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @edit_perm, @licensing_consortium_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @view_perm, @licensing_consortium_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @edit_perm, @negotiator_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @view_perm, @negotiator_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @edit_perm, @subscriber_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @view_perm, @subscriber_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @edit_perm, @subscription_consortium_rdv );
insert into org_perm_share(perm_id,rdv_id) values ( @view_perm, @subscription_consortium_rdv );

Ideally, I think we need some UI that lets an administrator set these values rather than having them in scripts.

Ian.

**Comment by ianibo** [comment]
Until next re-deploy, manually updated permissions as below:

mysql> select r.rdv_value, p.code, p.id perm, r.rdv_id role from org_perm_share ops, perm p , refdata_value r where ops.perm_id = p.id and ops.rdv_id = r.rdv_id;
+------------------------+------+------+------+
| rdv_value              | code | perm | role |
+------------------------+------+------+------+
| Licensee               | edit |    1 |    8 | 
| Licensee               | view |    2 |    8 | 
| Licensing Consortium   | edit |    1 |   91 | 
| Negotiator             | view |    2 |   90 | 
| Subscriber             | edit |    1 |   12 | 
| Subscriber             | view |    2 |   12 | 
| Subscription Consortia | edit |    1 |   82 | 
+------------------------+------+------+------+
7 rows in set (0.00 sec)

mysql> insert into org_perm_share(perm_id,rdv_id) values ( 2, 91 );
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> insert into org_perm_share(perm_id,rdv_id) values ( 2, 82 );
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> select r.rdv_value, p.code, p.id perm, r.rdv_id role from org_perm_share ops, perm p , refdata_value r where ops.perm_id = p.id and ops.rdv_id = r.rdv_id order by rdv_value;
+------------------------+------+------+------+
| rdv_value              | code | perm | role |
+------------------------+------+------+------+
| Licensee               | edit |    1 |    8 | 
| Licensee               | view |    2 |    8 | 
| Licensing Consortium   | edit |    1 |   91 | 
| Licensing Consortium   | view |    2 |   91 | 
| Negotiator             | view |    2 |   90 | 
| Subscriber             | edit |    1 |   12 | 
| Subscriber             | view |    2 |   12 | 
| Subscription Consortia | edit |    1 |   82 | 
| Subscription Consortia | view |    2 |   82 | 
+------------------------+------+------+------+
9 rows in set (0.00 sec)
