### ISSUE TITLE
A user with 'read only' membership of an Org can create Licences/Subscriptions

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#308]
E.g. user TestUserA: UoW ReadOnly [HH] / oaYDLonYlJRXD3hKbU30N1mn4YQ=@edina.ac.uk  
University_of_Westminster:2:INST_ADM
University_of_Westminster:1:INST_USER

Was able to copy and create licences for University of Westminster. Once created, permissions work fine (i.e. they can't edit the licences/subs they have created).

I understand that until it is created the licence/sub can't be protected by permissions.
Would it be possible to prevent them copying/creating licences by limiting access to URLs such as:
http://test.kbplus.ac.uk/kbplus/myInstitutions/University_of_Westminster/cleanLicense
http://test.kbplus.ac.uk/kbplus/licenseDetails/index/91?copy-licence=Copy+Selected&baselicense=1&shortcode=University_of_Westminster
http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/276?createSubAction=copy&subOfferedId=1&shortcode=University_of_Westminster

Unless you have Editor permissions under the Institution in the Path/Parameters?

I don't think this needs fixing for us to roll out to live though.

**Comment by ianibo** [comment]
This is not really cleanly specified. For now, I've hidden the addX buttons for licenses and subscriptions, and tried to redirect to the 401 page where perms aren't available. Needs a proper re-visit, tagging on perms things like this is dangerous because it's system wide and can break lots of stuff.. ideally an -early-in-phase- item. Please re-open with specific individual URLs if more issues.

**Comment by ostephens** [comment]
Can we revert the hiding of the addX buttons for licences and subscriptions - after running through with Helen I'm concerned this could stop 'view only' users carrying out tasks they need to (e.g. investigating JISC deals).
