### ISSUE TITLE
Revert to old styling on Licence details page

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#341]
Update to test on 18/01/2013 changed styling on licence details page (e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/index/30) - which has led to "Public?" flag field not being editable if it is not already set. Need to revert styling

**Comment by ianibo** [comment]
Done, but styling breaks on chrome. Asked chris to investigate.

**Comment by ianibo** [comment]
@nbrock Can one of you chaps take a peek at the license details screen under chrome? Not sure whats going on with it screencap below tho:
![image](https://f.cloud.github.com/assets/53283/80180/ae5afdde-6229-11e2-9d50-a143d0aadcae.png)
Cheers,
Ian.

**Comment by nathanbrock** [comment]
Hey Ian,

Sorry for my tardy reply! Thanks for pushing the commented out settings last week. I've not had chance to look at it just yet due to other project loads. I'll have a look into the previous issue (even though its been closed) and the one below on Wednesday is that's ok?

All the best!

Nathan

On 19 Jan 2013, at 11:16, Ian Ibbotson <notifications@github.com<mailto:notifications@github.com>> wrote:

@nbrockhttps://github.com/nbrock Can one of you chaps take a peek at the license details screen under chrome? Not sure whats going on with it screencap below tho:
[https://f.cloud.github.com/assets/53283/80180/ae5afdde-6229-11e2-9d50-a143d0aadcae.png]https://f.cloud.github.com/assets/53283/80180/ae5afdde-6229-11e2-9d50-a143d0aadcae.png
Cheers,
Ian.

**Comment by nathanbrock** [comment]
Hey Ian,

I've just pushed two minor changes to the stylesheet to try and resolve the before mentioned issue.  They can be found in the mm_changes branch.

There's are an increasingly amount I'm unable to test as I'm unable to traverse the latest version of the code base locally without running into permission errors (sometimes) or lacking data (like subs and licenses). Is there an updated version of the dev database I could possibly get my hands on for any future issues we may need to look at?

Cheers!

Nathan

On 19 Jan 2013, at 11:16, Ian Ibbotson <notifications@github.com<mailto:notifications@github.com>> wrote:

@nbrockhttps://github.com/nbrock Can one of you chaps take a peek at the license details screen under chrome? Not sure whats going on with it screencap below tho:
[https://f.cloud.github.com/assets/53283/80180/ae5afdde-6229-11e2-9d50-a143d0aadcae.png]https://f.cloud.github.com/assets/53283/80180/ae5afdde-6229-11e2-9d50-a143d0aadcae.png
Cheers,
Ian.
