### ISSUE TITLE
When a column selected for sorting on subs details page, a CSS issue affects display of column heading

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#371]
E.g. see http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/272?sort=tipp.title.title&order=asc

The 'Title' column heading does not display properly. This also applies to sorting by the other column headings:

Core status
Start date
End date
Core start date
Core end date

Same issues applies in other screens when clicking header for sorting, so I guess may be a sitewide CSS issue. However can submit issues for other screens if needed

**Comment by ianibbo** [comment]
Think this is because the up/down arrow icon is not no-repeat.. Probably
needs to be offset..

Need to discuss how we manage stuff like this... not really sure how to
resolve.

e

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
