### ISSUE TITLE
Broader title search when adding a new title

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#409]
When adding a new title via http://test.kbplus.ac.uk/kbplus/titleDetails/findTitleMatches is it possible to have the search for title to find partial matches? Acknowledged that this would give more 'false positives' but also decreases chances of adding duplicate titles by accident

**Comment by ianibo** [comment]
This can be done, but right now it uses the key title string, which does lower casing and other things. We did this as specced over the idea of using a porter-stemmed title match, which we thought might be better (Trimming of leading articles etc). My worry with this is that we'll miss titles that are already present, either by punctuation, other abbreviations or variant spellings. Since the use case here is title addition, and  not title search, I'm not sure this is the best idea. Will do it, but need to flag up concerns.
