### ISSUE TITLE
Denied access to view a package where user belongs to institution that is linked to subscribing consortium

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#509]
e.g. using TestUser6 - read only member of University of Huddersfield (on http://knowplusdev.edina.ac.uk/ as of 2013-06-07 11:44) cannot view (e.g.) http://knowplusdev.edina.ac.uk/kbplus/packageDetails/show/136.

This package has a 'Subscription Consortia' of JISC Collections, and University of Huddersfield is linked to JISC Collections as a consortium member

**Comment by ianibbo** [comment]
Sorry to be incredibly dense, but the testing doc I have with user accounts
in only goes as high as kb+test5. I've tried to guess what the credentials
might be for kb+test6 but can't seem to get on. Can someone give me the
dets pls.

We need to have a chat about how this works.. Because my copy is of the
live DB it's almost impossible for me to recreate these tests in a dev
environment and it makes it really hard to track down problems.

**Comment by ianibbo** [comment]
NVM.. TestUserE is now TestUser6 which is kb+user5. In now

Turns out only admins were able to view packages before. There are
currently no more granular restrictions on who can see what packages.
Changed perms so only user level access is needed.

**Comment by ianibo** [comment]
Closing. Please open new issue with more info if happens again.
