### ISSUE TITLE
After successful upload of an ONIX-PL licence, redirect to attached KB+ Licence not ONIX-PL licence

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#565]
If you upload a licence via http://test.kbplus.ac.uk/kbplus/licenseImport/doImport after successful upload you get directed to the onix-pl licence details screen - e.g. http://test.kbplus.ac.uk/kbplus/onixplLicenseDetails/index/5

Instead suggest after successful upload you should be directed to the created KB+ licence (in this case http://test.kbplus.ac.uk/kbplus/licenseDetails/index/543). Possibly to the ONIX-PL display within that licence (e.g. http://test.kbplus.ac.uk/kbplus/licenseDetails/onixpl/543) rather than just /index?

**Comment by neilmayo** [comment]
I've made this change - but note that an onix-pl licence (opl) can be associated with multiple concrete KB+ licences, so if you upload an opl that matches an existing licence, and choose to overwrite that license rather than create a new one, we can only link to either (a) the updated opl, or (b) the first of the existing licenses which are linked with the updated opl. For now I've implemented (a).

**Comment by ostephens** [comment]
Seems to work as expected
