### ISSUE TITLE
XML error on trying to use Serials Solution transformation

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#569]
Testing an export from http://test.kbplus.ac.uk/kbplus/myInstitutions/JISC_Collections/currentTitles/filtering-form?filterSub=all&filterPvd=all&filterHostPlat=all&filterOtherPlat=all&sort=tipp.title.title&order=asc&filter=research&validOn=2013%2F08%2F29

Export creates file with the error:
## 

<h1>Software error:</h1>

<pre>Error parsing the content of the xml -&gt; :58: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0xE9 0x65 0x6E 0x6E
  &lt;Title&gt;ALTER - European Journal of Disability Research / Revue Europ?enne de R
                                                                      ^
</pre>

<p>
For help, please send mail to the webmaster (<a href="mailto:you@example.com">you@example.com</a>), giving this error message 
and the time and date of the error.

</p>
## 

The XML export itself works OK, and I've checked the title and made sure the accented character is entered as UTF8

Is the transformation causing an issue here?

**Comment by desreid** [comment]
This is partially fixed now, in that the transformer no longer receives invalid utf-8. So, you do get back some transformed text, but the é character is mangled. Still working on this.

**Comment by ostephens** [comment]
Des - is the issue here with the original é character not being entered with the correct encoding, or is it that something is happening between the data entry and the xml being generated? If the former then I'd not expect it to be fixed as part of this work I don't think - it probably needs fixing at source

**Comment by desreid** [comment]
I would love to be able to blame the data, but I currently _think_ the data is OK in this particular case. You'll find that if you download the XML version of those titles, then the é looks fine. So something is going wrong after the XML is created.

**Comment by ianibbo** [comment]
P.s. The newer import process should be silently fixing most non utf8
character encodings. So even if duff data is uploaded file it should be
correct in the dB.

**Comment by desreid** [comment]
There were two steps to the fix:
1) Ensuring that the XML sent to the transformer was in fact UTF-8
2) Ensuring that the response from the transformer was passed on to the user's browser as UTF-8

Fixing 1) was a case of changing 
new InputStreamBody(new ByteArrayInputStream(content.getBytes()), reqMIME, 'file'))
to 
new InputStreamBody(new ByteArrayInputStream(content.getBytes("UTF-8")), reqMIME, 'file'))
and adding
main_response.setCharacterEncoding("UTF-8");

Fixing 2) involved using a writer instead of an outputstream to write to the client. A writer inherits the encoding correctly from the main_response object. An outputstream gets it from the environment.
