### ISSUE TITLE
List of IEs not showing for some subscriptions taken in data explorer

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#60]
e.g. http://knowplus.edina.ac.uk/kbplus/subscription/show/167 - doesn't show a list of entitlements

This is the only example I've found - so could be an issue with just this one subscription?

**Comment by ianibo** [comment]
When I look in the log files, this whole file reports titles as not having a publisher.

Because we have allowed title rows without a publisher through these are no longer reported as errors. I'm investigating the chain through the processing to see if I can find out why this is happening. Has this file been complete and available for a long while? Might it just have been added since the latest data load?

**Comment by ianibo** [comment]
Data shows up in latest dataload.

**Comment by ostephens** [comment]
Either I'm missing something or this is not resolved. Can chat on Skype if you have a mo

**Comment by ianibo** [comment]
You won't see the fixed data until I update the live system... probably
this evening.

Probably best to wait until I send a message to the list saying "updated"
then re-open if you still think it's broken.

On 3 July 2012 10:11, ostephens <
reply@reply.github.com

> wrote:
> 
> Either I'm missing something or this is not resolved. Can chat on Skype if
> you have a mo
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/k-int/KBPlus/issues/60#issuecomment-6729512

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
