### ISSUE TITLE
"New Package" announcements do not seem to be created on Live

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#652]
When a new package is created I'd expect this to create an Announcement, and post the announcement to Zendesk - see #605 

This doesn't seem to be happening at the moment on live (although did work on test when #605 closed)

**Comment by ianibo** [comment]
This is broken because of the change of system ID:
mysql> select \* from system_object;
+--------+---------+------------------+------------+
| sys_id | version | sys_ann_forum_id | sys_id_str |
+--------+---------+------------------+------------+
|      1 |       0 | NULL             | KB+        | 
|      2 |       1 | 20827643         | kbplus     | 
+--------+---------+------------------+------------+
2 rows in set (0.00 sec)

Which is causing problems.. Will delete the offending entry.

**Comment by ianibo** [comment]
Have cleaned up as much as possible. Live should be restarted.

**Comment by ostephens** [comment]
Fixed
