### ISSUE TITLE
Import Subscription Taken Worksheet not working on dev

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#729]
Trying to import a subs taken worksheet via Manage -> Import Subscription Taken Worksheet (e.g. http://demo.kbplus.ac.uk/kbplus/subscriptionImport/importSubscriptionWorksheet/35) after sheet upload no lines are shown on the screen (http://demo.kbplus.ac.uk/kbplus/subscriptionImport/importSubscriptionWorksheet/35 again)

Possible mis-type of '12' as '21' line 625 SubscriptionImportController.groovy?

**Comment by ianibbo** [comment]
Right - the same routine is used for both sub take and renewals as it
happens  - so it's either broken for imports with the jusp stats in, or
it's broken for subs upload (Because one has the jusp stats and the other
doesn't).

I'm pondering what to do

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
