### ISSUE TITLE
Write SQL to list all Titles with no IDs in the ISSN or eISSN namespace

### ISSUE THREAD

**Issue by desreid** [k-int/KBPlus#791]

**Comment by desreid** [comment]
I have written a query that I think will do this, based on the contents of the identifier_namespace.idns_ns column, but it's returning 21197 rows. Were you expecting that many, or does that sound wrong? The SQL is 

```
SELECT ti.ti_id, ti.ti_title FROM title_instance ti WHERE ti.ti_id NOT IN (SELECT ti.ti_id FROM title_instance ti LEFT JOIN identifier_occurrence imp ON imp.io_id = ti.ti_imp_id LEFT JOIN identifier i ON i.id_id = imp.io_canonical_id LEFT JOIN identifier_namespace iname ON iname.idns_id = i.id_ns_fk WHERE iname.idns_ns = 'eISSN') AND ti.ti_id NOT IN (SELECT ti.ti_id FROM title_instance ti LEFT JOIN identifier_occurrence imp ON imp.io_id = ti.ti_imp_id LEFT JOIN identifier i ON i.id_id = imp.io_canonical_id LEFT JOIN identifier_namespace iname ON iname.idns_id = i.id_ns_fk WHERE iname.idns_ns = 'ISSN');
```

**Comment by ostephens** [comment]
Yes - that's far too many.
Two issues I think:

The io_id is the ID for the identifier_occurrence  - it doesn't key to the title at all - the title key in the identifier_occurrence table is the io_ti_fk
The ti_imp_id is an ID created on import, but not used as an FK in the db - the ti_id is used as an FK in other tables

so where you have imp.io_id = ti.ti_imp_id  I think you want imp.io_ti_fk = ti.ti_id

**Comment by desreid** [comment]
OK, I see. 
The corrected SQL then is

```
 SELECT ti.ti_id, ti.ti_title FROM title_instance ti WHERE ti.ti_id NOT IN (SELECT ti.ti_id FROM title_instance ti LEFT JOIN identifier_occurrence imp ON imp.io_ti_fk = ti.ti_id LEFT JOIN identifier i ON i.id_id = imp.io_canonical_id LEFT JOIN identifier_namespace iname ON iname.idns_id = i.id_ns_fk WHERE iname.idns_ns = 'eISSN') AND ti.ti_id NOT IN (SELECT ti.ti_id FROM title_instance ti LEFT JOIN identifier_occurrence imp ON imp.io_ti_fk = ti.ti_id LEFT JOIN identifier i ON i.id_id = imp.io_canonical_id LEFT JOIN identifier_namespace iname ON iname.idns_id = i.id_ns_fk WHERE iname.idns_ns = 'ISSN');
```

This now give 1077 results, does that sound more like it? 

Here's a sample of 5

 22342 | Quarterly Bulletin of the Association of Industrial Medical Officers                                                                                                                                                                                                                                           | 
| 22362 | Journal of Public Administration                                                                                                                                                                                                                                                                               | 
| 22364 | Language Teaching and Linguistics: Abstracts                                                                                                                                                                                                                                                                   | 
| 22371 | Vocational Aspect of Secondary and Further Education                                                                                                                                                                                                                                                           | 
| 22425 | APA Mental Hospital Service Bulletin

**Comment by ianibo** [comment]
Hey des, That looks better. When I run on my DB locally I get 1664 rows, which is the same as when I run my alternate SQL.

Since the aim of getting Edina to write this SQL was to do a bit of knowledge transfer ready for the 4.2 handover, here is my version of the SQL to do the same job

SET @issn_type_id = null, @eissn_type_id=null, @doi_type_id=null;;
select @issn_type_id:=idns_id from identifier_namespace where idns_ns='ISSN';
select @eissn_type_id:=idns_id from identifier_namespace where idns_ns='eISSN';
select @doi_type_id:=idns_id from identifier_namespace where idns_ns='DOI';

select ti.ti_id, ti_title
from title_instance as ti
where not exists ( select io.io_id
                     from identifier_occurrence as io,
                          identifier as id
                   where io_ti_fk = ti.ti_id
                     and io.io_canonical_id = id_id
                      and id.id_ns_fk in ( @issn_type_id, @eissn_type_id, @doi_type_id ) );

It's pretty similar - I cheat a bit by setting up variables for the identifier types - but that makes it a bit more extensible if we add/remove other class one identifiers. The other major difference is my use of not exists rather than not in, which I think will keep your DBA a bit happier. This gives rise to the following execution plan:
+----+--------------------+-------+--------+-----------------------------------------+--------------------+---------+---------------------------+-------+-------------+
| id | select_type        | table | type   | possible_keys                           | key                | key_len | ref                       | rows  | Extra       |
+----+--------------------+-------+--------+-----------------------------------------+--------------------+---------+---------------------------+-------+-------------+
|  1 | PRIMARY            | ti    | ALL    | NULL                                    | NULL               | NULL    | NULL                      | 21256 | Using where |
|  2 | DEPENDENT SUBQUERY | io    | ref    | FKF0533F279B08D7A5,FKF0533F27B37DC426   | FKF0533F27B37DC426 | 9       | KBPlus.ti.ti_id           |     1 | Using where |
|  2 | DEPENDENT SUBQUERY | id    | eq_ref | PRIMARY,FK9F88ACA9F1F42470,id_value_idx | PRIMARY            | 8       | KBPlus.io.io_canonical_id |     1 | Using where |
+----+--------------------+-------+--------+-----------------------------------------+--------------------+---------+---------------------------+-------+-------------+

Rather than the original 
+----+--------------------+-------+--------+-----------------------------------------+--------------------+---------+----------------------------+-------+-------------+
| id | select_type        | table | type   | possible_keys                           | key                | key_len | ref                        | rows  | Extra       |
+----+--------------------+-------+--------+-----------------------------------------+--------------------+---------+----------------------------+-------+-------------+
|  1 | PRIMARY            | ti    | ALL    | NULL                                    | NULL               | NULL    | NULL                       | 21256 | Using where |
|  3 | DEPENDENT SUBQUERY | ti    | eq_ref | PRIMARY                                 | PRIMARY            | 8       | func                       |     1 | Using index |
|  3 | DEPENDENT SUBQUERY | imp   | ref    | FKF0533F279B08D7A5,FKF0533F27B37DC426   | FKF0533F27B37DC426 | 9       | func                       |     1 | Using where |
|  3 | DEPENDENT SUBQUERY | i     | eq_ref | PRIMARY,FK9F88ACA9F1F42470,id_value_idx | PRIMARY            | 8       | KBPlus.imp.io_canonical_id |     1 | Using where |
|  3 | DEPENDENT SUBQUERY | iname | eq_ref | PRIMARY                                 | PRIMARY            | 8       | KBPlus.i.id_ns_fk          |     1 | Using where |
|  2 | DEPENDENT SUBQUERY | ti    | eq_ref | PRIMARY                                 | PRIMARY            | 8       | func                       |     1 | Using index |
|  2 | DEPENDENT SUBQUERY | imp   | ref    | FKF0533F279B08D7A5,FKF0533F27B37DC426   | FKF0533F27B37DC426 | 9       | func                       |     1 | Using where |
|  2 | DEPENDENT SUBQUERY | i     | eq_ref | PRIMARY,FK9F88ACA9F1F42470,id_value_idx | PRIMARY            | 8       | KBPlus.imp.io_canonical_id |     1 | Using where |
|  2 | DEPENDENT SUBQUERY | iname | eq_ref | PRIMARY                                 | PRIMARY            | 8       | KBPlus.i.id_ns_fk          |     1 | Using where |
+----+--------------------+-------+--------+-----------------------------------------+--------------------+---------+----------------------------+-------+-------------+

Hope thats helpful in some way going forward.

Ian.

**Comment by desreid** [comment]
"Since the aim of getting Edina to write this SQL was to do a bit of knowledge transfer ready for the 4.2 handover, here is my version of the SQL to do the same job" That's new to me I'm afraid, Ian. If I'm duplicating work here, then this is not efficient.

**Comment by ianibbo** [comment]
Not duplicating work - I needed the list for something else (Title history
parsing), and I realised my approach was different to yours - and AFAIK the
reason for this was to take another towards the edina being responsible for
everything so k-int should start and hand stuff like this over - I just
thought it was an opportunity to share approaches and knowledge. Sorry.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Yes - 1077 results seems more likely. Note that Ian's SQL differs slightly in that it looks for titles that don't have ISSN, eISSN or DOI - which happens to give the same results, but just noting this.

Technically this is what the data managers have asked for, but now I look at the output I can't help but think that they really could do with the record status (ti.ti_status_rv_fk and value from rdv_value.rdv_id) in here as well. Not sure if this complicates matters substantially as I note that ti.ti_status_rv_fk is often NULL. Essentially this is so the data managers can see where a TI record has been given a status of 'deleted' - where they'd expect there to be no identifiers present anyway.

**Comment by desreid** [comment]
Ian's version of the query can easily be tweaked like this to include the status of the title that you want:

```
select ti.ti_id, rv.rdv_value, ti_title
from title_instance as ti LEFT JOIN refdata_value rv ON rv.rdv_id = ti.ti_status_rv_fk
where not exists ( select io.io_id
from identifier_occurrence as io,
identifier as id
where io_ti_fk = ti.ti_id
and io.io_canonical_id = id_id
and id.id_ns_fk in ( @issn_type_id, @eissn_type_id, @doi_type_id ) );
```

Obviously you still need to set the variables first as before.

**Comment by ostephens** [comment]
Thanks - are you able to send the output of this report to Magaly?

**Comment by desreid** [comment]
OK, I've sent the output to the dev list and Magaly.

**Comment by desreid** [comment]
Christina has got back to me to say that a refinement of this is required. 

> should be titles with NO identifiers so no ISSN, EISSN, ISBN, EISBN (as there are ebook entries in the original list that has been sent)

Reopening ticket and assigning to self.

**Comment by desreid** [comment]
There is no reference to EISBN in the identifier_namespace table, but I was able to exclude ISBN (actually isbn) as requested. This excludes about 500 rows, but there seem to be lots of new ones since I last ran this query. So the total has now gone up to 1517. The query is now:

```
SET @issn_type_id = NULL, @eissn_type_id=NULL, @isbn_type_id=NULL;
SELECT @issn_type_id:=idns_id FROM identifier_namespace WHERE idns_ns='ISSN';
SELECT @eissn_type_id:=idns_id FROM identifier_namespace WHERE idns_ns='eISSN';
SELECT @isbn_type_id:=idns_id FROM identifier_namespace WHERE idns_ns='isbn';

SELECT ti.ti_id, ti_title
FROM title_instance AS ti
WHERE NOT EXISTS ( SELECT io.io_id
FROM identifier_occurrence AS io,
identifier AS id
WHERE io_ti_fk = ti.ti_id 
AND io.io_canonical_id = id_id
AND id.id_ns_fk IN ( @issn_type_id, @eissn_type_id, @isbn_type_id ) );
```

**Comment by desreid** [comment]
New list sent to Christina, closing.

**Comment by desreid** [comment]
Just heard from Magaly to ask me to run the query again after some data changes described by DK as:

> Unexpected unattached Title records arising from the Des report - we're almost certain now that all the records concerned came from a rogue test run; Ian is doing a final check and once certain he will clean up; I guess we should run the Des report again thereafter. There is no danger that other stuff was wrongly inserted.

**Comment by desreid** [comment]
The query now returns 1542 rows, so perhaps the above comment doesn't refer to this query. Am clarifying with Magaly.

**Comment by ianibbo** [comment]
For info..

I've had separate conversations with david about this - the situation is
considerably more complex than the simple one that was first identified /
pointed at.

I've started to add some SQL to tidy the data in the UPDATE.sql to be run
with the latest release, as requested by the DMs but also warned david that
it's critical that the DMs check the data on test after the delete. The
rogue run does not account for the majority of problem cases (it just
happened to highlight a wider issue) possibly a hangover from very early on
in the project.

Anyway - also discussing this end and trying to find a sensible way forward.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
