### ISSUE TITLE
ToDos should not be displayed on dashboard for 'deleted' subscriptions / licences

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#802]
Current if a ToDo is created on a subscription, it displays on the dashboard no matter the status of the subscription. Similarly with licences.

If the Subscription or Licence has status 'Deleted' the user should not see ToDo items for that Sub/License on the dashboard.

e.g. see http://test.kbplus.ac.uk/kbplus/myInstitutions/Newcastle_University/dashboard - second To Do item is

http://test.kbplus.ac.uk/kbplus/subscriptionDetails/index/1412

Looking at http://test.kbplus.ac.uk/kbplus/subscription/show/1412 this sub has status 'Deleted'

**Comment by ianibo** [comment]
Ioannis is looking into this but I think this is not doable easily. It is not easy to link from a ToDO to the source license or subscription when doing an aggregate query (Like the one needed to only show header level info with "4 changes" button).

Also - Personally, would prefer issues to be of the imperative form "Don't display todos for deleted objects.." rather than the value based observation "X Should not" which sounds like something is wrong, when really it's a feature being requested.

**Comment by ostephens** [comment]
Thanks Ian.

Perhaps the issue could be restated as 'Users don't want To Dos that relate to deleted objects' - that is if an easier solution is to not to create Pending changes for things that are deleted in the first place I think that would also meet the user requirement.

This rang a bell, and checking we've had this request previously #711

**Comment by ianibbo** [comment]
Thats actually _much_ easier, cheers!

Ioannis - do this?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
