### ISSUE TITLE
Spotlight Index

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#815]
Spotlight should return subscriptions and licences too

**Comment by ostephens** [comment]
I thought it already did? This is something that concerned me a bit but was waiting for user feedback. I don't think generally people are going want to see Subs/Licences that they can't view via the Spotlight search - might be better to leave them out?

**Comment by iyawnis** [comment]
It looks like the problem was with my local ES. Subscriptions showing. In that case I will leave licences out and review if we want subscriptions out eventually

**Comment by ostephens** [comment]
Can we take out Subscriptions - I think this is going to cause problems and confusion for users

**Comment by ianibbo** [comment]
Anything more specific? We absolutely can, but I thought the point of this
was to find absolutely anything?

Guess I'm just trying to understand the source of the confusion?

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Issue is that for any particular user most subscriptions cannot be viewed - because they are for other institutions. Subscriptions across institutions tend of have the same, or very similar, names. So if you search (e.g.) "ACLS" via Spotlight search you get a list of 10 subscriptions all called "ACLS Humanities E-Book 2011-2014" - all coming from different institutions. Screenshot to illustrate:

![screen shot 2014-11-13 at 17 32 15](https://cloud.githubusercontent.com/assets/576174/5033145/5583c352-6b5b-11e4-8755-20db9e575ec2.png)

If I click on any of these as (for example) a user from University of Westminster, then I get the message (as expected) "You do not have permission to view the requested page" 

If there is some way of only showing subscriptions/licences to which the user has access then that would work fine, but I'm guessing this would be difficult to achieve?

**Comment by ianibbo** [comment]
Ah yes.. Very much /agree that users should only see their own subs. We
should fix.. Pondering.

**Comment by ostephens** [comment]
Yes Licences as well, but with a slight complication. Licences with type equivalent to RefData Value 'Template' can be seen by anyone. Licences with type equivalent to RefData value 'Actual' only by members of licensee org

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by iyawnis** [comment]
It looks like we are not currently having licences in ES... I will look into adding them once I get the filtering for subs working properly.

**Comment by ostephens** [comment]
OK
Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by iyawnis** [comment]
91941a27a14cc555a7a4cd118a850ddf7f8c6d11

**Comment by ostephens** [comment]
Checked on dev.kbplus.ac.uk (built from newdev) and looks like this is now successfully just searching Subs to which the logged in user has access.

Not currently searching Licences (as previously and as noted in comments)
