### ISSUE TITLE
On ‘Manage Users’ screen clearly indicate users who are KB+ Editors/Administrators

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#894]
Row 39 in Enhancement request.

I assume this refers to userDetails/list screen.
Instead of highlighting rows or something similar, I have added another filter which allows to find users based on roles. You believe that will enough?

![screenshot from 2015-04-29 11 08 10](https://cloud.githubusercontent.com/assets/2336352/7388831/6e3b9838-ee60-11e4-8949-4d5a35a14134.png)

**Comment by iyawnis** [comment]
The dropdown includes all the available values of Role.authority

**Comment by ostephens** [comment]
Have checked and this actually refers to the Org/users page:
https://www.kbplus.ac.uk/kbplus/organisations/users/390

On this page Institutional admins want to know those users who are KB+ Editors/Admins so that when they see unfamiliar names on the list they don't just delete them/revoke permissions.

So this needs to be indicate on the list somewhere, not via a filter

**Comment by iyawnis** [comment]
So the scenario where 'Ioannis' who is an ROLE_ADMIN, is also a read-only user for OrgB, he should be highlighted/flagged  as admin in OrgB user list ?

**Comment by iyawnis** [comment]
Also does it matter to distinguish admin / kbplus_editors ?

**Comment by Damyantipatel** [comment]
I think the institution admins want to be clear who the people on the list are, so perhaps if as part of the name it is indicated that they are jisc staff ie user: Damyanti Patel (JISC)

**Comment by ostephens** [comment]
The issue this request is trying to tackle is that when a member of an institution looks at the list of users  who have access to their institutional data they need to be able to answer the question "Who are these people and why do these people have access to my institutions data?"

I think there are the following possibilities:
- The person belongs to the institution in question and so has access
- The person is a KB+ Data Manager or Support staff (e.g. K-Int/Sero staff)
- The person shouldn't really have access and they've been added to the institution in error

I think information that could be displayed on this user list that might help users understand who and why of the users in the list are:

Display name
Email address
If they have KB_EDITOR or ROLE_ADMIN roles (would be better if these could be displayed as 'KB+ Editor' or 'KB+ Administrator' rather than just the Role labels
Institution that the user has a Default Dashboard [possibly - not sure about this last one?]

So display could be something like:

![screen shot 2015-04-29 at 17 59 14](https://cloud.githubusercontent.com/assets/576174/7396501/7d31902a-ee99-11e4-9976-6a2647c692df.png)

The Institution in brackets after the name is their default dashboard (unless there is a better way of getting their 'home' institution)

**Comment by iyawnis** [comment]
Ok this is clear enough Owen thanks.

**Comment by iyawnis** [comment]
![screenshot from 2015-04-30 11 11 32](https://cloud.githubusercontent.com/assets/2336352/7410747/b9a113e2-ef29-11e4-8d1e-ddf701864d47.png)
