### ISSUE TITLE
Add search options to Public Export page

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#898]
'OS: I would like to propose that we should remove the current ‘Public Exports’ page and replace with a publicly viewable ES driven page' 

Are we looking for a page same as 'All Packages'but  with export options ? Will we need to have  package Identifiers as well?

**Comment by ostephens** [comment]
That was the general idea, but I think I need to write a more detailed proposal for this and get approval from the Jisc team before we move forward with it.

Do you see any particular issues in doing something similar to All Packages but public facing?
What data do we have available in the ES index for packages?

**Comment by iyawnis** [comment]
The ES will provide the data for searching packages. Once a package is
selected for export, the same functions that we currently use will be
called (mysql). We will only need to add the additional package IDs tp ES
but that is not an issue.

**Comment by iyawnis** [comment]
Work in progress, I think we need something different in the exports links instead of having that same text over and over again ? any ideas? That Identifier is wrong I just added it as a test 

![screenshot from 2015-05-11 16 29 25](https://cloud.githubusercontent.com/assets/2336352/7568492/041c3724-f7fb-11e4-8f0f-3ef647e87598.png)

**Comment by iyawnis** [comment]
Also I think there is no need for identifier column I guess, could be on a row bellow name which same cell

**Comment by iyawnis** [comment]
![screenshot from 2015-05-11 16 50 31](https://cloud.githubusercontent.com/assets/2336352/7568991/dc7e90ec-f7fd-11e4-8bde-9a56c923cc46.png)

**Comment by iyawnis** [comment]
@ostephens any feedback? I am thinking of a dropdown menu 'formats' in the Export column...

**Comment by ostephens** [comment]
@latusaki generally looks good to me. Some comments/questions:
- Can 'last modified' be included as a search option? So you could 'find stuff modified since X date' for someone who wants to know which packages have changed?
- Change the facet order on the left to be the same as in the 'All Package' Search (i.e. Consortia, Provider, Start date, End date)
- Display the start/end date in the results table (as All Package search)
- Display the Consortium in the results table (as All Package search)
- Can we have an option to 'find current packages' (i.e. ones where the start date is in the past and the end date in the future)? (either specific option, or through search params?)

In terms of Exports I think I prefer having the direct links in the page but some questions about exports:
- Currently the JSON export on this page is different to the JSON export offered by packageDetails/show/{package_id}?format=json - it would be nice to move to a single JSON export, would it be possible to use the latter one?
- Currently the CSV exports are generated by specific code. I wonder if we should move to the same mechanism used from /packageDetails/show/{package_id}?format=xml&transformId={transform_id} - which would mean one less place to manage export formats
- If we move to using the single JSON export, we might want to offer the XML export /packageDetails/show/{package_id}?format=xml alongside JSON

@ianibbo might have opinions about the export options...

**Comment by ostephens** [comment]
NB I still haven't heard back from Jisc Collections about this as an overall approach (see my email sent 7th May subject 'Changes to public export screen'

**Comment by iyawnis** [comment]
I think dropdown should be considered, as I find there is a lot of wasted screen space if we have all the exports links. Also, currently you can sort by date modified,  but I can add a filter if needed.

Following feedback from Magaly or Kristen (can't remember) only current packages are available for export. 
![screenshot from 2015-05-12 14 43 54](https://cloud.githubusercontent.com/assets/2336352/7588554/d1001552-f8b5-11e4-9e0e-e0a643c8e6d1.png)
![screenshot from 2015-05-12 14 44 17](https://cloud.githubusercontent.com/assets/2336352/7588555/d10104da-f8b5-11e4-959a-03e93a5113e2.png)

**Comment by iyawnis** [comment]
![screenshot from 2015-05-12 14 40 24](https://cloud.githubusercontent.com/assets/2336352/7588558/daec9f9a-f8b5-11e4-83a0-b228e41dd6ed.png)

**Comment by iyawnis** [comment]
Also, we will need specification for the 'public Package details' page(The one that will be accessible from clicking packages in package export) . This includes what fields should be in, as well as layout.

**Comment by ostephens** [comment]
I think we should separate out the need for a public Package details screen as a different issue - that may need quite a bit more discussion I think - so just leave them un-linked for now

**Comment by ostephens** [comment]
Agreed the Exports dropdown looks better. I'm slightly concerned it is an extra click for people, but maybe that's OK as it definitely improves the look a lot!

**Comment by ostephens** [comment]
I think a filter for date modified would be valuable. I think this needs to be an 'updated since' option so you can see all the stuff updated since you last checked.

If this is already filtering only for current packages that's great  - just note that in the screenshots you are showing non-current packages

**Comment by iyawnis** [comment]
Right, I think I had TIPPs in mind. I assume filtering for current packages should be optional? or applied everywhere ?

**Comment by ostephens** [comment]
Optional

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by iyawnis** [comment]
Does the 'Package Field' search filter make sense ? It was named Package Name before, but the query can be on any field so I thought this should be more clear.. 
![screenshot from 2015-05-20 11 47 15](https://cloud.githubusercontent.com/assets/2336352/7724071/17deca14-fee6-11e4-9943-f808ffdf2955.png)

**Comment by ostephens** [comment]
I'd make it more general like "Query Term"

**Comment by ostephens** [comment]
Or "Search Term" is perhaps clearer

**Comment by iyawnis** [comment]
Added 'Current Packages' as a pill option, and 'Modified after' search criteria (can rename to Updated Since if you prefer it). Do we need something more on UI side? (other than specification for public package view) 
![screenshot from 2015-05-20 15 43 40](https://cloud.githubusercontent.com/assets/2336352/7728465/48747dc4-ff07-11e4-93ae-00d3908c5b0c.png)
![screenshot from 2015-05-20 15 43 19](https://cloud.githubusercontent.com/assets/2336352/7728468/4aec2282-ff07-11e4-8bdc-db59219152bd.png)

**Comment by ostephens** [comment]
Looks good.
Did you have anything specific in mind on the UI side? Nothing I can think of immediately

**Comment by iyawnis** [comment]
No just checking. In that case I will start looking at the export changes you suggested.

**Comment by iyawnis** [comment]
Will create new issues after you have a chance to test this.
