### ISSUE TITLE
Implement Title Sort key on all screens where titles sort is an option

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#902]
A bit confused by this. Does it say to make sure we can sort by title, wherever TitleInstance is used, or is this about sortTitle attribute of TitleInstance ?

row 235

**Comment by ostephens** [comment]
It's about using sortTitle attribute of TitleInstance as the sort key whenever we offer sort by Title. Does that that make sense?

Possibly incomplete list of screens, but in priority order

/subscriptionDetails/index/
/packageDetails/show/
/myInstitutions/{orgshortcode}/currentTitles
/subscriptionDetails/addEntitlements/
/subscriptionDetails/previous/
/subscriptionDetails/expected/
/packageDetails/current/
/packageDetails/expected/
/packageDetails/previous/

**Comment by ostephens** [comment]
Oh - and we should check that the sort key is populated for all titles and that it is updated after a title edit...

If we think sometimes will need to regenerate all sort keys possibly a new admin option to 'generate title sort keys' so we can force re-generation across the db?

**Comment by iyawnis** [comment]
Right, I understand now, will look into it. Although why would we use TitleInstance.sortTitle when sorting by title? Isn't this likely to make users confused when the sort order is different that what they see?

**Comment by ostephens** [comment]
The situation currently is confusing - lower/upper case sort separately and non-ascii character also affect the sort - meaning that you don't get the sort you expect anyway.

Also users expect "The Journal of Blah" to sort as "Journal of Blah" because typically library systems ignore terms such as 'The' when sorting

**Comment by ianibbo** [comment]
Yeah ioannis.. You're right to be a bit confused. In the library world
there is an approach that pre dates setting the collation sequence to one
that ignores diacritics and case. That's what we're doing here. There are
special rules about ignoring leading articles like the, a, ... Which this
approach makes possible.. Which is why were going down this route :) ok?

**Comment by iyawnis** [comment]
@ostephens for the subscriptionController/index example. Do I live the screen as it is, and when sorting use sortTitle, or do I need to make some visual change as well so that the above is clear ?

**Comment by iyawnis** [comment]
On my local database there are many titles that do not have a generated sort title. This can cause problems with the sorting as one would guess. Looking at the code there is no process to do that, and sortTitle only updates when the title instance is updated (that doesnt include updating identifiers etc)

**Comment by iyawnis** [comment]
select count(ti_id) from title_instance where sort_title is null;
returns 24k on my DB

**Comment by iyawnis** [comment]
I have added a new job that will be run once on startup and generate sortTitle for all TI. The sort by title has been changed to use sortTitle instead on the listed pages.
