### ISSUE TITLE
Core: Display Core status in relation to the Subscription being viewed

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#908]
In order that the user can tell whether a title was Core for a specific subscription, when displaying the Core status on:

/subscriptionDetails/index/
/issueEntitlement/show/

Use the 'asAt' date already used for displaying IEs on /subscriptionDetails/index. The basic logic of this is to assess the value using the current date if the subscription end date is in the future, or the subscription end date if this is in the past.

See also #909 for change in values displayed for Core status in Subscriptions/IE screens

**Comment by iyawnis** [comment]
Just to clarify that I understand correctly, the asAt date is only usable within subscriptionDetails/index.

**Comment by ostephens** [comment]
Ah
OK so that leaves the Q of what to do on the IE screen
Perhaps on the IE screen we can show the actual dates rather than the calculated status - as we've got room?

**Comment by iyawnis** [comment]
And leave the users to calculate the status? You think they can handle it ? :P 
There are already a lot of things in that screen, and its scheduled for rework on 5.0 (not sure of priority).
I could possibly copy the table that you get on the edit popup to be static within IE screen if you believe we should do that. Or we can use same flags as in tipview screen (now) instead of (this sub)

**Comment by ostephens** [comment]
As you say that screen already flagged for some re-work.
Since we want to get this functionality out asap, I think go for the quicker of the two options to implement
