### ISSUE TITLE
"Transfer to another title" option on the Tipp page

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#919]
Add an option to change the TitleInstance a TIPP is pointing to

**Comment by latusaki** [comment]
@ostephens  Is this the same issue as #992 or is another another Title transfer that we need for TIPPs?

**Comment by ianibo** [comment]
After discussion we're concerned that this raises lots of questions, and would rather have a proper worked up spec that explains the required behaviour and all side effects.

**Comment by iyawnis** [comment]
@ostephens  any updates on this ?

**Comment by ostephens** [comment]
I think this is straightforward:

There are situations where TIPPs have been created against the wrong TI - see https://kbplus.zendesk.com/agent/tickets/495
The TIPPs need to be moved so they are linked to the correct TI (i.e. update tipp_ti_fk with the correct TI ID)
Suggest rather than adding to TIPP page (as in title of this issue) we add an option in 'Admin Actions -> Data Management Tasks' to 'Move TIPPs between Titles'
Form with a box for TIPP ID and TI ID to move it to

Note this is different to the current 'Merge TI' which moves _all_ TIPPs from one TI to another TI. This is selective movement of TIPPs between TIs and doesn't carry the implication that one TI should be deleted.

**Comment by iyawnis** [comment]
Ok, so there are no  constraints to check? User will just give a TIPP ID and a TI ID, and then the given TIPP will be referencing the given TI.

**Comment by ostephens** [comment]
No I don't think there are any constraints to check
