### ISSUE TITLE
Viewing 'public' journal licences requires login

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#978]
To view a 'public' journal licence (e.g. https://www.kbplus.ac.uk/test/public/journalLicences?journal=issn:0747-0088&org=2107) requires a login, even if the "Public Journal Access" property for the Org is set to 'Public'

**Comment by ianibbo** [comment]
Changed the config on the web server - not an app thing - can't do
conditional securing under shib, so it will be a matter of not displaying
rather than securing.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
OK - cheers. Going to go to users to ask for feedback at this point
