### ISSUE TITLE
Test: "Expunge Deleted Titles" fails to delete a title with status 'Deleted'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#995]
Title https://www.kbplus.ac.uk/test/titleInstance/edit/28536 has Status = Deleted (title_instance.ti_status_rv_fk = 284)

Run the 'Expunge Deleted Titles" using https://www.kbplus.ac.uk/test/dataManager/expungeDeletedTitles

This does not seem to delete the title (unless the async job triggered takes much longer than expected? Checked after 30 minutes)

**Comment by ianibbo** [comment]
It does take a while

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ianibbo** [comment]
Just checked and delete is still running on test

Test is woefully underpowered, be best not to report issues like this to
support until absolutely certain they are not artfacts of Jisc inability to
run a shared service. Jisc have been given every opportunity to sort out
the infrastructure - it's not fair to keep incurring cost [against fixed
price] investigating things like this against k-int because Jisc can't get
it's act together.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
Ok

**Comment by ostephens** [comment]
Confirmed deleted now job run to completion - apologies.

**Comment by ianibbo** [comment]
Ah no worries at all on your front - really need to sort out this service
hosting stuff tho - reached the end of my absently amused stage now. I
thought we were going to deal with this under the shared service stuff -
but I think Liam and I must have been at cross purposes on it because I
don't really see how we're going to work it in at the moment - so I can't
really see a sensible forum to deal with this in.

Was just checking and looks like everything completed OK all the same.

Cheers!
e

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com
